# Headers for result
REQUEST_ID_HEADER = "request_id"
START_TIME_HEADER = "end_to_end_start"
END_TIME_HEADER = "end_to_end_end"
LOAD_GEN_START_TIME_HEADER = "end_to_end_load_gen_start"
LOAD_GEN_END_TIME_HEADER = "end_to_end_load_gen_end"

COMMON_HEADERS = [
    REQUEST_ID_HEADER,
    START_TIME_HEADER,
    END_TIME_HEADER,
    LOAD_GEN_START_TIME_HEADER,
    LOAD_GEN_END_TIME_HEADER,
]


NODES_PATH_HEADER = "nodes_path"
TOTAL_INPUT_TOKENS_HEADER = "total_input_tokens"
TOTAL_OUTPUT_TOKENS_HEADER = "total_output_tokens"
QUESTION_HEADER = "question"
ACTUAL_ANSWER_HEADER = "actual_answer"
EXPECTED_ANSWER_HEADER = "expected_answer"
CORRECT_HEADER = "correct"

EXTRA_HEADERS = [
    NODES_PATH_HEADER,
    TOTAL_INPUT_TOKENS_HEADER,
    TOTAL_OUTPUT_TOKENS_HEADER,
    QUESTION_HEADER,
    ACTUAL_ANSWER_HEADER,
    EXPECTED_ANSWER_HEADER,
]

RESULT_HEADERS = COMMON_HEADERS + EXTRA_HEADERS
