workflow: "self_rag"
verbose: true

cores: "16-31"

retriever:
    embedding:
        provider: "openai"
        model: "text-embedding-3-small"
    split: true
    chunk_size: 2000
    chunk_overlap: 200
    search_type: "similarity"
    search_kwargs:
        k: 10

retrieval_grader:
    provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0
    skip: true

generator:
    provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0.2

hallucination_grader:
    provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0
    skip: true

answer_grader:
    provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0
    skip: true

question_rewriter:
    provider: "openai"
    model: "gpt-4o-mini"
    temperature: 0.2
