import os
import base64
import mimetypes
from typing import TypedDict, NotRequired, List, Dict
import openai
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph
import time
import video_processor
from response_structure import MCQAnswer
import json
from pydub import AudioSegment

from datasets import load_dataset
import logging
import io

import json

import requests


def track_latency(node_name: str):
    def decorator(func):
        def wrapper(state: GraphState) -> GraphState:
            start_time = time.time()
            result_state = func(state)
            end_time = time.time()
            
            if "latency_tracker" not in result_state:
                result_state["latency_tracker"] = {}
            
            result_state["latency_tracker"][node_name] = {"start_time": start_time,
                                                          "end_time": end_time}
            
            return result_state
        return wrapper
    return decorator


class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        question: The question to ask about the image.
        answer: The answer generated by the OpenAI model.
        image_url: The URL or data URI of the image to process.
        image_path: The local path of the image to process.
    """
    question: NotRequired[str]
    answer: NotRequired[str]
    image_urls: NotRequired[List[str]]
    image_paths: NotRequired[List[str]]
    video_path: NotRequired[str]
    video_transcription: NotRequired[str]
    config: NotRequired[dict]
    audio_clips: NotRequired[List[AudioSegment]]
    token_stats: NotRequired[dict]
    latency_tracker: NotRequired[Dict[str, Dict[str, float]]]
    start_time: NotRequired[float]
    end_time: NotRequired[float]

def encode_images(state: GraphState) -> GraphState:
    """
    Encodes a list of local images into a list of data URI formats.
    This node is only called for local image workflows.
    """
    logging.info("---ENCODING MULTIPLE LOCAL IMAGES---")
    if not state.get("image_paths"):
        raise ValueError("No image paths found in state to encode.")

    encoded_urls = []
    for image_path in state["image_paths"]:
        try:
            with open(image_path, "rb") as image_file:
                base64_image = base64.b64encode(image_file.read()).decode('utf-8')
            
            mime_type, _ = mimetypes.guess_type(image_path)
            if mime_type is None:
                mime_type = "image/jpeg"

            encoded_urls.append(f"data:{mime_type};base64,{base64_image}")
        except FileNotFoundError:
            print(f"Error: The file was not found at {image_path}")
            raise
        except Exception as e:
            print(f"An error occurred while encoding {image_path}: {e}")
            raise
    
    # This node's job is to populate the 'image_urls' key for the model node.
    state["image_urls"] = encoded_urls
    logging.info("---IMAGES ENCODED SUCCESSFULLY---")
    return state

@track_latency("encode-videos")
def encode_videos(state: GraphState) -> GraphState:
    """
    Encodes a video in a list of frames in URI formats. This node is 
    only called for local video workflows
    """
    state["start_time"] = time.time()

    logging.info("---ENCODING LOCAL VIDEO---")
    if not state.get("video_path"):
        raise ValueError("No video path found in state to encode")
    if not state.get("config"):
        raise ValueError("No config found in state for video encoding")
    
    encoded_urls = []
    video_path = state["video_path"]
    config = state["config"]
    default_num_frames = config["workflow_settings"]["default_num_frames"]
    meta_data = video_processor.get_metadata(video_path)

    # get frames and transcription if transcription is enabled
    if config["inputs"]["video_mme_input"]["transcription"]:
        frames, audio_clips = video_processor.get_frames_and_audio_in_range(video_path, 0.0, meta_data["duration"], max(meta_data["duration"]//default_num_frames, 1))
        for frame in frames:
            encoded_urls.append(video_processor.encode_image(frame))

        state["audio_clips"] = audio_clips
        state["image_urls"] = encoded_urls
        logging.info("---VIDEO ENCODED SUCCESSFULLY---")
        return state
    else:
        frames = video_processor.get_num_frames(video_path, 0.0, meta_data["duration"], max(meta_data["duration"]//default_num_frames, 1))
        for frame in frames:
            encoded_urls.append(video_processor.encode_image(frame))

        state["image_urls"] = encoded_urls
        logging.info("---VIDEO ENCODED SUCCESSFULLY---")
        return state
    
@track_latency("speech_to_text")
def speech_to_text_transcription(state: GraphState) -> GraphState:
    """
    does speech to text transcription given a list of audioclips. This node is
    only called if transcription is needed for the query.
    """
    logging.info("SPEECH TO TEXT")
    audio_clips = state["audio_clips"]
    full_audio = audio_clips[0]

    audio_bytes = io.BytesIO()
    full_audio.export(audio_bytes, format="mp3")
    audio_bytes.seek(0) # Rewind the buffer to the beginning
    
    WHISPER_API_BASE = "http://localhost:7771/v1"
    WHISPER_API_KEY = "not-needed" # The speaches container doesn't require a key

    # --- Initialize the correct client ---
    stt_client = openai.OpenAI(
        base_url=WHISPER_API_BASE,
        api_key=WHISPER_API_KEY,
    )
    try:
        # Pass a tuple containing a filename and the BytesIO object
        transcription = stt_client.audio.transcriptions.create(
            model="Systran/faster-whisper-tiny.en",
            file=("audio.mp3", audio_bytes)
        )
        
        print("Transcription Successful!")
        print(transcription.text)
        state["video_transcription"] = transcription.text


    except Exception as e:
        print(f"An error occurred: {e}")
    logging.info("DONE SPEECH TO TEXT")
    return state
    
@track_latency("generate_answer")
def generate_answer(state: GraphState) -> GraphState:
    """
    This node uses a model to generate an answer to the question about the images.
    It receives image URLs either from the initial input or from the 'encoder' node.
    """
    logging.info("---CALLING MODEL TO GENERATE ANSWER--")

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OpenAI API key not found. Please set the OPENAI_API_KEY environment variable.")

    llm = ChatOpenAI(model="gpt-4o", openai_api_key=api_key)
    structured_llm = llm.with_structured_output(MCQAnswer)

    if not state.get("image_urls"):
        raise ValueError("No image URLs found in state. The encoder may have failed or no URLs were provided.")
    if not state.get("question"):
        raise ValueError("No question found in state.")
    question = state["question"]
    transcription = state["video_transcription"]
    if transcription:
        prompt_text = (
            "Please answer the following question based on the provided video frames and the video's transcription.\n\n"
            f"**Video Transcription:**\n{transcription}\n\n"
            f"**Question:**\n{question}"
        )
    else:
        prompt_text = question

    # Start building the content list with the text prompt
    message_content = [{"type": "text", "text": prompt_text}]
    
    # Add each image to the content list
    for url in state["image_urls"]:
        message_content.append({
            "type": "image_url",
            "image_url": {"url": url},
        })

    message = HumanMessage(content=message_content)
    logging.info("INVOKING MODEL")
    response = llm.invoke([message])
    logging.info("FINISHED INVOCATION")
    state["answer"] = response.content
    # state["answer"] = response.answer.value
    logging.info("FINISHED GENERATING ANSWER")

    end_time = time.time()
    if state["start_time"]:
        state["end_time"] = end_time
    else:
        raise KeyError("logging not right")
    return state


@track_latency("generate_answer_vllm")
def generate_answer_vllm(state: GraphState) -> GraphState:
    """
    This node uses a vLLM-hosted model to generate an answer.
    It connects to the local vLLM server using the ChatOpenAI client.
    """
    logging.info("---GENERATING ANSWER USING VLLM-HOSTED MODEL---")

    # Define the location of your vLLM OpenAI-compatible server.
    # It's good practice to use an environment variable.
    config = state["config"]
    # vllm_api_base = os.getenv("VLLM_API_BASE", "http://localhost:8000/v1")
    vllm_api_base = config["model_config"]["vllm"]["api_base"]
    mcq_schema = MCQAnswer.model_json_schema()
    # Instantiate the ChatOpenAI client, pointing it to your local vLLM server.
    # The API key can be a dummy value as vLLM doesn't require it by default.

    extra_body={
        "structured_outputs": {
            "json": mcq_schema
        }
    }

    llm = ChatOpenAI(
        model=config["model_config"]["vllm"]["model"],
        openai_api_key="not-needed",
        openai_api_base=vllm_api_base,
        extra_body=extra_body
    )

    if not state.get("image_urls"):
        raise ValueError("No image URLs found in state. The encoder may have failed or no URLs were provided.")
    if not state.get("question"):
        raise ValueError("No question found in state.")
    
    question = state["question"]
    transcription = state.get("video_transcription")

    # If a transcription exists, combine it with the question
    if transcription:
        prompt_text = (
            "Please answer the following question based on the provided video frames and the video's transcription.\n\n"
            f"**Video Transcription:**\n{transcription}\n\n"
            f"**Question:**\n{question}"
        )
    else:
        prompt_text = question

    # Build the multimodal message content
    message_content = [{"type": "text", "text": prompt_text}]
    for url in state["image_urls"]:
        message_content.append({
            "type": "image_url",
            "image_url": {"url": url},
        })

    # Create the HumanMessage and invoke the model
    message = HumanMessage(content=message_content)
    logging.info("---INVOKING VLLM-HOSTED MODEL---")
    response = llm.invoke([message])
    logging.info("---FINISHED INVOCATION---")

    token_usage = response.response_metadata.get("token_usage", {})

    if "token_stats" not in state:
        state["token_stats"] = {}
    state["token_stats"]= {
        "prompt_tokens": token_usage.get("prompt_tokens", 0),
        "completion_tokens": token_usage.get("completion_tokens", 0),
        "total_tokens": token_usage.get("total_tokens", 0),
    }

    # The response content should be a JSON string thanks to guided decoding.
    # We parse it into our Pydantic object for clean, validated access.
    parsed_content = json.loads(response.content)
    state["answer"] = MCQAnswer(**parsed_content)
    logging.info("---FINISHED GENERATING ANSWER---")

    end_time = time.time()
    if state["start_time"]:
        state["end_time"] = end_time
    else:
        raise KeyError("logging not right")
    
    return state

# --- Conditional Routing Function ---
def route_images(state: GraphState):
    """
    This conditional node acts as a router. It checks the state to decide
    which path to take next.
    """
    # ("---ROUTING---")
    if "image_paths" in state and state["image_paths"]:
        # If local image paths are provided, we need to encode them first.
        # print("---ROUTE: ENCODE LOCAL IMAGES---")
        return "encoder"
    elif "image_urls" in state and state["image_urls"]:
        # If image URLs are already present, we can go directly to the model.
        # print("---ROUTE: PROCESS URLS---")
        return "model"
    elif "video_path" in state and state["video_path"]:
        # print("---ROUTE: PROCESS VIDEO---")
        return "video_encoder"
    else:
        raise ValueError("No image paths or URLs provided in the initial state.")
    
def transcription_route(state: GraphState):
    if "audio_clips" in state and state["audio_clips"]:
        return "speech_to_text"
    elif "image_urls" in state and state["image_urls"]:
        return "model"
    else:
        raise ValueError("no audio_clips or frames present")
    

def warmup_models(app: StateGraph, config: dict):
    """
    Sends a trivial request to all configured models to warm them up.
    This mitigates cold start latency on the first real request.
    """
    logging.info("--- WARMING UP MODELS ---")
    
    base_url = "http://localhost:7771/v1"
    model_id = "Systran/faster-whisper-tiny.en"

    requests.post(f"{base_url}/models/{model_id}")


    video_paths = [f for f in os.listdir(config["inputs"]["video_mme_input"]["videos_path"])]
    video_ids = [os.path.splitext(path)[0] for path in video_paths][:1]

    input = []

    ds = load_dataset("lmms-lab/Video-MME")
    short_ds = ds.filter(lambda example: example["duration"] == "short")
    for row in short_ds["test"]:
        if row["videoID"] in video_ids:
            idx = video_ids.index(row["videoID"])
            video_input = {"video_path": config["inputs"]["video_mme_input"]["videos_path"] + '/' +  video_paths[idx],
            "question": f'Based on the materials provided answer the question by picking an option. \n Question: {row["question"]} \n Options: {row["options"]}',
            "config": config
            }
            input.append(video_input)

    final_state_data = app.batch(input)
    logging.info("FINISHED WARMUP")